#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "SpaceVim"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    guifont = "Overpass Mono:h11"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    automatic_update = true
    # Linux Kernel style 
    # default_indent = 8
    # expand_tab = false


# SpaceVim default layer contains no plugins, but It provides some better default config for SpaceVim.
[[layers]]
  name = "default"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "treesitter"

#[[layers]]
#  name = "lsp"
#  filetypes = [
#    "rust",
#    "c",
#    "cpp"
#  ]

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "lang#ipynb"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#python"
  format_on_save = true
  python_file_head = [
    '#!/usr/bin/env python',
    '# -*- coding: utf-8 -*-',
    '',
    ''
  ]

[[layers]]
  name = "lang#r"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name = "lang#markdown"

# Messes up with Org files (adds newlines before tags...)
# [[layers]]
#  name = "lang#org"

 [[layers]]
  name = "lang#plantuml"
  plantuml_jar_path = "/usr/share/java/plantuml/plantuml.jar"

[[layers]]
    name = "lang#scheme"
    scheme_dialect = "chez-scheme"
    scheme_interpreter = "/usr/bin/chez-scheme"

[[layers]]
    name = "lang#sh"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#cmake"

[[layers]]
  name = "sudo"

[[layers]]
  name = "ssh"

[[layers]]
  name = "git"
  git_plugin = "gina"

[[layers]]
  name = "fzf"

[[layers]]
  name = "ctrlspace"

[[layers]]
  name = "format"
  enable = true
  format_on_save = false

[[layers]]
  name = "exprfold"

[[layers]]
  name = "tools"

[[layers]]
  name = "edit"

[[layers]]
  name = "debug"

[[layers]]
    name = "incsearch"
