;; -*- lexical-binding: t; -*-

;; This file can be used to override `minemacs-modules'
;; and `minemacs-core-modules'

;; (setq minemacs-core-modules
;;       '(defaults     ;; Tweak Emacs defaults
;;         splash       ;; Simple splash screen (inspired by emacs-splash)
;;         bootstrap    ;; Bootstrap straight.el
;;         core-ui      ;; Theme and modeline
;;         keybindings  ;; general.el, which-key, hydra, ...
;;         evil         ;; evil, evil-collection, evil-mc, ...
;;         completion))   ;; vertico, marginalia, corfu, cape, consult, ...

;; (setq minemacs-modules
;;       '(ui           ;; popwin, focus, writeroom-mode, emojify, ...
;;         editor       ;; undo-fu-session, unicode-fonts, ligature, ...
;;         vc           ;; magit, forge, core-review, diff-hl, ...
;;         prog         ;; tree-sitter, eglot, realgud, editorconfig, ...
;;         lisp         ;; parinfer-rust, macrostep, geiser, elisp, ...
;;         data         ;; csv, yaml, toml, json, ...
;;         org          ;; org, org-modern, ...
;;         notes        ;; org-roam, deft, ...
;;         email        ;; mu4e, mu4e-alert, org-msg, ...
;;         docs         ;; pdf-tools, nov, ...
;;         spell        ;; spell-fu, eglot-ltex, ...
;;         files        ;; dirvish, dired, ...
;;         tools        ;; vterm, tldr, rg, ...
;;         biblio       ;; org-cite, citar, ...
;;         daemon       ;; Emacs daemon tweaks
;;         rss          ;; elfeed, ...
;;         ros          ;; ros
;;         eaf          ;; EAF apps (browser, jupyter, file-sender, ...)
;;         math))       ;; maxima, ...
